// Pre-built category library with 15+ clues each
// Players can pick from these during setup, and host can still upload images on top

export const CATEGORY_LIBRARY = {
  "Animals": [
    { clue: "King of the jungle", answer: "Lion" },
    { clue: "Black and white bamboo eater", answer: "Panda" },
    { clue: "Tallest land animal", answer: "Giraffe" },
    { clue: "Largest ocean mammal", answer: "Blue Whale" },
    { clue: "Striped horse-like animal", answer: "Zebra" },
    { clue: "Pouch-carrying Australian hopper", answer: "Kangaroo" },
    { clue: "Eight-armed ocean creature", answer: "Octopus" },
    { clue: "Slow-moving shell carrier", answer: "Turtle" },
    { clue: "Man's best friend", answer: "Dog" },
    { clue: "Night hunter with silent wings", answer: "Owl" },
    { clue: "Trunk and big ears", answer: "Elephant" },
    { clue: "Colorful tropical talker", answer: "Parrot" },
    { clue: "Fastest land animal", answer: "Cheetah" },
    { clue: "Venomous eight-legged spinner", answer: "Spider" },
    { clue: "Hump-backed desert traveler", answer: "Camel" },
    { clue: "Pink long-legged wading bird", answer: "Flamingo" },
    { clue: "Masked nocturnal trash raider", answer: "Raccoon" },
  ],
  "Bible Characters": [
    { clue: "Built an ark for the flood", answer: "Noah" },
    { clue: "Shepherd boy who defeated a giant", answer: "David" },
    { clue: "Swallowed by a great fish", answer: "Jonah" },
    { clue: "Strongest man in the Bible", answer: "Samson" },
    { clue: "First man created by God", answer: "Adam" },
    { clue: "Led Israel out of Egypt", answer: "Moses" },
    { clue: "Sold into slavery by brothers", answer: "Joseph" },
    { clue: "Denied Jesus three times", answer: "Peter" },
    { clue: "Wise king who built the temple", answer: "Solomon" },
    { clue: "Thrown into the lions den", answer: "Daniel" },
    { clue: "Tax collector who climbed a tree", answer: "Zacchaeus" },
    { clue: "Mother of Jesus", answer: "Mary" },
    { clue: "Betrayed Jesus for 30 silver coins", answer: "Judas" },
    { clue: "First murderer in the Bible", answer: "Cain" },
    { clue: "Father of many nations", answer: "Abraham" },
    { clue: "Rebuilt the walls of Jerusalem", answer: "Nehemiah" },
  ],
  "Worship Songs": [
    { clue: "How great is our ___", answer: "God" },
    { clue: "Amazing ___ how sweet the sound", answer: "Grace" },
    { clue: "10,000 reasons to bless the ___", answer: "Lord" },
    { clue: "Way maker, miracle ___", answer: "Worker" },
    { clue: "What a beautiful ___ we carry", answer: "Name" },
    { clue: "Reckless ___", answer: "Love" },
    { clue: "Good good ___", answer: "Father" },
    { clue: "Build my life upon Your ___", answer: "Love" },
    { clue: "No longer ___ but alive in Christ", answer: "Slaves" },
    { clue: "Here I am to ___", answer: "Worship" },
    { clue: "Oceans where feet may ___", answer: "Fail" },
    { clue: "Great are You ___", answer: "Lord" },
    { clue: "In Christ ___ my hope is found", answer: "Alone" },
    { clue: "Holy ___ You are worthy", answer: "Spirit" },
    { clue: "Blessed be Your ___", answer: "Name" },
  ],
  "Movies": [
    { clue: "Boy wizard with a lightning scar", answer: "Harry Potter" },
    { clue: "Ogre who lives in a swamp", answer: "Shrek" },
    { clue: "Let it go, ice powers princess", answer: "Frozen" },
    { clue: "Toys come alive when no one looks", answer: "Toy Story" },
    { clue: "A galaxy far far away", answer: "Star Wars" },
    { clue: "Finding a lost clownfish son", answer: "Finding Nemo" },
    { clue: "Superhero team with infinity stones", answer: "Avengers" },
    { clue: "Boy raised by jungle animals", answer: "Jungle Book" },
    { clue: "Ring must be destroyed in a volcano", answer: "Lord of the Rings" },
    { clue: "Dinosaur theme park gone wrong", answer: "Jurassic Park" },
    { clue: "Lion cub becomes king of Pride Rock", answer: "Lion King" },
    { clue: "Spider-bitten teen becomes a hero", answer: "Spider-Man" },
    { clue: "Dream within a dream within a dream", answer: "Inception" },
    { clue: "Robot cleans up Earth alone", answer: "Wall-E" },
    { clue: "Genie in a lamp grants wishes", answer: "Aladdin" },
    { clue: "Italian plumber saves a princess", answer: "Mario" },
  ],
  "Countries": [
    { clue: "Land of the rising sun", answer: "Japan" },
    { clue: "Home of the Eiffel Tower", answer: "France" },
    { clue: "Great Wall is here", answer: "China" },
    { clue: "Land of kangaroos and koalas", answer: "Australia" },
    { clue: "Boot-shaped European country", answer: "Italy" },
    { clue: "Home of the Amazon rainforest", answer: "Brazil" },
    { clue: "Pyramids and the Sphinx", answer: "Egypt" },
    { clue: "Maple leaf flag country", answer: "Canada" },
    { clue: "Land of tacos and sombreros", answer: "Mexico" },
    { clue: "Taj Mahal is located here", answer: "India" },
    { clue: "Dracula's homeland in Eastern Europe", answer: "Romania" },
    { clue: "Largest country by land area", answer: "Russia" },
    { clue: "Land of Vikings and fjords", answer: "Norway" },
    { clue: "Island nation famous for sushi", answer: "Japan" },
    { clue: "Home of Big Ben and the Queen", answer: "England" },
    { clue: "Land of tulips and windmills", answer: "Netherlands" },
  ],
  "Food & Drinks": [
    { clue: "Italian pie with cheese and sauce", answer: "Pizza" },
    { clue: "Frozen treat on a cone", answer: "Ice Cream" },
    { clue: "Morning drink made from beans", answer: "Coffee" },
    { clue: "Yellow curved tropical fruit", answer: "Banana" },
    { clue: "Fizzy brown cola drink", answer: "Coca-Cola" },
    { clue: "Japanese rolled rice and fish", answer: "Sushi" },
    { clue: "Mexican wrapped tortilla meal", answer: "Burrito" },
    { clue: "Chocolate chip baked treat", answer: "Cookie" },
    { clue: "Red sauce pasta dish", answer: "Spaghetti" },
    { clue: "Grilled patty in a bun", answer: "Hamburger" },
    { clue: "Fried potato sticks", answer: "French Fries" },
    { clue: "Morning meal with syrup", answer: "Pancakes" },
    { clue: "Bubbly Italian water drink", answer: "Sparkling Water" },
    { clue: "Crunchy Mexican corn chip", answer: "Nachos" },
    { clue: "Layered Italian pasta dish", answer: "Lasagna" },
  ],
  "Sports": [
    { clue: "Dribbling and slam dunks", answer: "Basketball" },
    { clue: "Touchdown and field goals", answer: "Football" },
    { clue: "Home run and batting", answer: "Baseball" },
    { clue: "Goals, pitch, and offsides", answer: "Soccer" },
    { clue: "Love means zero in this sport", answer: "Tennis" },
    { clue: "Puck on ice with sticks", answer: "Hockey" },
    { clue: "18 holes and a tiny white ball", answer: "Golf" },
    { clue: "Pins and a heavy rolling ball", answer: "Bowling" },
    { clue: "Net, sand, and spikes", answer: "Volleyball" },
    { clue: "Gloves and a knockout punch", answer: "Boxing" },
    { clue: "Flip, vault, and balance beam", answer: "Gymnastics" },
    { clue: "Laps in a pool", answer: "Swimming" },
    { clue: "Racket and shuttlecock", answer: "Badminton" },
    { clue: "Hurdles and sprinting on a track", answer: "Track and Field" },
    { clue: "Board and waves", answer: "Surfing" },
  ],
  "Video Games": [
    { clue: "Block-building survival sandbox", answer: "Minecraft" },
    { clue: "Battle royale with building", answer: "Fortnite" },
    { clue: "Plumber rescues a princess", answer: "Super Mario" },
    { clue: "Catch them all with Pokeballs", answer: "Pokemon" },
    { clue: "Green hero saves Hyrule", answer: "Zelda" },
    { clue: "Blue hedgehog runs fast", answer: "Sonic" },
    { clue: "Soccer with rocket-powered cars", answer: "Rocket League" },
    { clue: "Block-stacking puzzle from Russia", answer: "Tetris" },
    { clue: "Five nights surviving animatronics", answer: "FNAF" },
    { clue: "Among us crewmates and imposters", answer: "Among Us" },
    { clue: "Open world horse-riding cowboys", answer: "Red Dead Redemption" },
    { clue: "Plant defenders against undead", answer: "Plants vs Zombies" },
    { clue: "Italian brothers in go-karts", answer: "Mario Kart" },
    { clue: "Blocky characters in a battle arena", answer: "Roblox" },
    { clue: "Tiny fighters on a big stage", answer: "Smash Bros" },
  ],
  "Books of the Bible": [
    { clue: "First book, creation story", answer: "Genesis" },
    { clue: "Israel leaves Egypt", answer: "Exodus" },
    { clue: "Songs and poems of praise", answer: "Psalms" },
    { clue: "Wisdom sayings of Solomon", answer: "Proverbs" },
    { clue: "Prophecy about a coming Messiah", answer: "Isaiah" },
    { clue: "Story of a faithful foreign woman", answer: "Ruth" },
    { clue: "Jesus birth and ministry, first Gospel", answer: "Matthew" },
    { clue: "Early church history and missions", answer: "Acts" },
    { clue: "Paul writes about faith and grace", answer: "Romans" },
    { clue: "Love chapter is in this letter", answer: "1 Corinthians" },
    { clue: "Apocalyptic visions and the end", answer: "Revelation" },
    { clue: "The shortest Gospel", answer: "Mark" },
    { clue: "Man tested by suffering and loss", answer: "Job" },
    { clue: "Walls rebuilt around Jerusalem", answer: "Nehemiah" },
    { clue: "Queen who saved her people", answer: "Esther" },
    { clue: "Prophet swallowed by a fish", answer: "Jonah" },
  ],
  "Flags": [
    { clue: "Red white and blue with stars and stripes", answer: "USA" },
    { clue: "Red circle on white background", answer: "Japan" },
    { clue: "Maple leaf on red and white", answer: "Canada" },
    { clue: "Green white and red vertical stripes", answer: "Italy" },
    { clue: "Blue white and red horizontal stripes", answer: "France" },
    { clue: "Union Jack cross pattern", answer: "United Kingdom" },
    { clue: "Green and gold with a diamond", answer: "Brazil" },
    { clue: "Red with five yellow stars", answer: "China" },
    { clue: "Orange white and green horizontal", answer: "India" },
    { clue: "Blue yellow and red vertical stripes", answer: "Romania" },
    { clue: "Black red and gold horizontal", answer: "Germany" },
    { clue: "Red and white with crescent moon", answer: "Turkey" },
    { clue: "Blue with yellow stars in a circle", answer: "European Union" },
    { clue: "Green with a white crescent and star", answer: "Pakistan" },
    { clue: "White cross on a red background", answer: "Switzerland" },
  ],
  "Dinosaurs": [
    { clue: "King of the dinosaurs, tiny arms", answer: "T-Rex" },
    { clue: "Three horns and a frill", answer: "Triceratops" },
    { clue: "Long neck gentle giant", answer: "Brachiosaurus" },
    { clue: "Plates along its back", answer: "Stegosaurus" },
    { clue: "Clever pack hunter with claws", answer: "Velociraptor" },
    { clue: "Flying reptile, not a dinosaur", answer: "Pterodactyl" },
    { clue: "Armored tank with a club tail", answer: "Ankylosaurus" },
    { clue: "Sail-backed meat eater", answer: "Spinosaurus" },
    { clue: "Duck-billed herbivore", answer: "Parasaurolophus" },
    { clue: "Tiny two-legged fast runner", answer: "Compsognathus" },
    { clue: "Largest land predator ever", answer: "Giganotosaurus" },
    { clue: "Dome-headed headbutter", answer: "Pachycephalosaurus" },
    { clue: "Giant ocean predator, not a dino", answer: "Mosasaurus" },
    { clue: "Feathered early bird ancestor", answer: "Archaeopteryx" },
    { clue: "Huge South American herbivore", answer: "Argentinosaurus" },
  ],
  "Candy & Snacks": [
    { clue: "Colorful button-shaped chocolates", answer: "M&Ms" },
    { clue: "Twisted salty baked dough", answer: "Pretzel" },
    { clue: "Rainbow-colored fruit chews", answer: "Skittles" },
    { clue: "Chocolate bar with caramel and nougat", answer: "Snickers" },
    { clue: "Gummy bear-shaped candies", answer: "Gummy Bears" },
    { clue: "Red and white peppermint stick", answer: "Candy Cane" },
    { clue: "Orange cheese-dusted puffs", answer: "Cheetos" },
    { clue: "Peanut butter inside chocolate cups", answer: "Reeses" },
    { clue: "Sour worm-shaped gummies", answer: "Sour Worms" },
    { clue: "Crunchy triangle-shaped corn chips", answer: "Doritos" },
    { clue: "Swirled red and white hard candy", answer: "Peppermint" },
    { clue: "Chocolate-covered wafer fingers", answer: "Kit Kat" },
    { clue: "Tiny colorful candy-coated beans", answer: "Jelly Beans" },
    { clue: "Crunchy goldfish-shaped crackers", answer: "Goldfish" },
    { clue: "Hard candy on a stick", answer: "Lollipop" },
  ],
  "Space": [
    { clue: "Closest star to Earth", answer: "Sun" },
    { clue: "Red planet, possible future home", answer: "Mars" },
    { clue: "Planet with famous rings", answer: "Saturn" },
    { clue: "Earths only natural satellite", answer: "Moon" },
    { clue: "Largest planet in our system", answer: "Jupiter" },
    { clue: "Milky spiral we live in", answer: "Milky Way" },
    { clue: "Icy space traveler with a tail", answer: "Comet" },
    { clue: "Was a planet, now a dwarf", answer: "Pluto" },
    { clue: "First man to walk on the moon", answer: "Neil Armstrong" },
    { clue: "Orbiting telescope named after a scientist", answer: "Hubble" },
    { clue: "Invisible space trap, nothing escapes", answer: "Black Hole" },
    { clue: "Explosive death of a massive star", answer: "Supernova" },
    { clue: "Space agency with the rocket logo", answer: "NASA" },
    { clue: "International home orbiting Earth", answer: "ISS" },
    { clue: "Hottest planet due to greenhouse gases", answer: "Venus" },
  ],
  "Dog Breeds": [
    { clue: "Golden friendly family dog", answer: "Golden Retriever" },
    { clue: "Spotted firehouse mascot", answer: "Dalmatian" },
    { clue: "Tiny purse-sized Mexican dog", answer: "Chihuahua" },
    { clue: "Wrinkly-faced snoring companion", answer: "Bulldog" },
    { clue: "German police and military dog", answer: "German Shepherd" },
    { clue: "Fluffy white cloud-like small dog", answer: "Pomeranian" },
    { clue: "Long body, short legs, wiener shape", answer: "Dachshund" },
    { clue: "Curly hypoallergenic smart dog", answer: "Poodle" },
    { clue: "Sled-pulling Arctic working dog", answer: "Husky" },
    { clue: "Black and tan loyal guard dog", answer: "Rottweiler" },
    { clue: "Fastest dog breed, racing hound", answer: "Greyhound" },
    { clue: "Big fluffy mountain rescue dog", answer: "Saint Bernard" },
    { clue: "Small floppy-eared royal favorite", answer: "Corgi" },
    { clue: "Chocolate or yellow lab retriever", answer: "Labrador" },
    { clue: "Wrinkly Chinese fighting dog", answer: "Shar Pei" },
  ],
  "Famous Landmarks": [
    { clue: "Iron tower in Paris", answer: "Eiffel Tower" },
    { clue: "Ancient wonder in Giza Egypt", answer: "Pyramids" },
    { clue: "Green lady in New York harbor", answer: "Statue of Liberty" },
    { clue: "Leaning building in Italy", answer: "Tower of Pisa" },
    { clue: "Great stone wall across China", answer: "Great Wall" },
    { clue: "White marble tomb in India", answer: "Taj Mahal" },
    { clue: "Ancient Roman arena for gladiators", answer: "Colosseum" },
    { clue: "Giant carved faces in South Dakota", answer: "Mount Rushmore" },
    { clue: "Christ statue overlooking Rio", answer: "Christ the Redeemer" },
    { clue: "Red rock formation in Australia", answer: "Uluru" },
    { clue: "Ancient stone circle in England", answer: "Stonehenge" },
    { clue: "Tallest building in the world, Dubai", answer: "Burj Khalifa" },
    { clue: "Golden Gate crossing in San Francisco", answer: "Golden Gate Bridge" },
    { clue: "Ancient Greek hilltop temple", answer: "Parthenon" },
    { clue: "Giant carved Buddha in Japan", answer: "Great Buddha" },
  ],
  "Instruments": [
    { clue: "Six strings and a pick", answer: "Guitar" },
    { clue: "88 black and white keys", answer: "Piano" },
    { clue: "Sticks hitting stretched skins", answer: "Drums" },
    { clue: "Brass horn with three valves", answer: "Trumpet" },
    { clue: "Bow across four strings", answer: "Violin" },
    { clue: "Wooden reed wind instrument", answer: "Clarinet" },
    { clue: "Slide in and out brass instrument", answer: "Trombone" },
    { clue: "Small four-string Hawaiian instrument", answer: "Ukulele" },
    { clue: "Handheld squeezebox with buttons", answer: "Accordion" },
    { clue: "Metal keys hit with mallets", answer: "Xylophone" },
    { clue: "Double reed orchestral woodwind", answer: "Oboe" },
    { clue: "Largest string instrument", answer: "Double Bass" },
    { clue: "Silver sideways-blown wind instrument", answer: "Flute" },
    { clue: "Scottish bag-squeezed wind instrument", answer: "Bagpipes" },
    { clue: "Plucked string triangular instrument", answer: "Harp" },
  ],
  "Holidays": [
    { clue: "December 25th gift-giving celebration", answer: "Christmas" },
    { clue: "Spooky costumes and candy night", answer: "Halloween" },
    { clue: "Egg hunt and resurrection Sunday", answer: "Easter" },
    { clue: "Turkey dinner and gratitude", answer: "Thanksgiving" },
    { clue: "Hearts, chocolates, and roses", answer: "Valentines Day" },
    { clue: "Fireworks on Americas birthday", answer: "Fourth of July" },
    { clue: "Wearing green and finding clovers", answer: "St Patricks Day" },
    { clue: "New beginning at midnight countdown", answer: "New Years" },
    { clue: "Eight nights of candles and dreidels", answer: "Hanukkah" },
    { clue: "Honoring mothers with flowers", answer: "Mothers Day" },
    { clue: "Honoring working people in September", answer: "Labor Day" },
    { clue: "Remembering fallen soldiers in May", answer: "Memorial Day" },
    { clue: "Celebrating Martin Luther King Jr", answer: "MLK Day" },
    { clue: "Groundhog predicts more winter", answer: "Groundhog Day" },
    { clue: "Pancake and costume festival before Lent", answer: "Mardi Gras" },
  ],
  "Superheroes": [
    { clue: "Web-slinging New York teenager", answer: "Spider-Man" },
    { clue: "Dark knight of Gotham City", answer: "Batman" },
    { clue: "Man of steel from Krypton", answer: "Superman" },
    { clue: "Green rage monster scientist", answer: "Hulk" },
    { clue: "Genius billionaire in iron suit", answer: "Iron Man" },
    { clue: "Norse god with a hammer", answer: "Thor" },
    { clue: "Star-spangled soldier with a shield", answer: "Captain America" },
    { clue: "Amazon warrior princess", answer: "Wonder Woman" },
    { clue: "King of Wakanda", answer: "Black Panther" },
    { clue: "Fastest man alive in red suit", answer: "The Flash" },
    { clue: "Clawed mutant with healing powers", answer: "Wolverine" },
    { clue: "Underwater king of Atlantis", answer: "Aquaman" },
    { clue: "Master of mystical arts, doctor", answer: "Doctor Strange" },
    { clue: "Shrinking hero who talks to insects", answer: "Ant-Man" },
    { clue: "Green lantern ring bearer", answer: "Green Lantern" },
  ],
  "Cartoons": [
    { clue: "Yellow family in Springfield", answer: "The Simpsons" },
    { clue: "Sponge who lives in a pineapple", answer: "SpongeBob" },
    { clue: "Boy with a magic dog named Jake", answer: "Adventure Time" },
    { clue: "Talking Great Dane solves mysteries", answer: "Scooby-Doo" },
    { clue: "Pink starfish best friend", answer: "Patrick Star" },
    { clue: "Three super-powered little girls", answer: "Powerpuff Girls" },
    { clue: "Boy genius with a big head", answer: "Jimmy Neutron" },
    { clue: "Ninja turtles who love pizza", answer: "TMNT" },
    { clue: "Cat and mouse always chasing", answer: "Tom and Jerry" },
    { clue: "Avatar who controls all elements", answer: "Avatar Aang" },
    { clue: "Pink bunny and yellow duck friends", answer: "Courage the Cowardly Dog" },
    { clue: "Gravity Falls mystery twins", answer: "Gravity Falls" },
    { clue: "Ice king chasing princesses", answer: "Adventure Time" },
    { clue: "Squirrel scientist from Texas underwater", answer: "Sandy Cheeks" },
    { clue: "Regular guys at a park", answer: "Regular Show" },
  ],
  "Science": [
    { clue: "H2O chemical formula", answer: "Water" },
    { clue: "Force that keeps us on the ground", answer: "Gravity" },
    { clue: "Closest star to Earth", answer: "Sun" },
    { clue: "Building blocks of all matter", answer: "Atoms" },
    { clue: "Gas we breathe to survive", answer: "Oxygen" },
    { clue: "Speed of this is 186,000 miles per second", answer: "Light" },
    { clue: "Double helix that carries genetic code", answer: "DNA" },
    { clue: "Table with 118 elements", answer: "Periodic Table" },
    { clue: "Process plants use to make food from sunlight", answer: "Photosynthesis" },
    { clue: "Theory of evolution scientist", answer: "Darwin" },
    { clue: "E equals mc squared genius", answer: "Einstein" },
    { clue: "Layer protecting Earth from UV rays", answer: "Ozone" },
    { clue: "Molten rock erupting from Earth", answer: "Lava" },
    { clue: "Brain chemical that makes you happy", answer: "Dopamine" },
    { clue: "Smallest unit of life", answer: "Cell" },
  ],
  "C.S. Lewis Books": [
    { clue: "The ___, the Witch and the Wardrobe", answer: "Lion" },
    { clue: "Prince ___", answer: "Caspian" },
    { clue: "The Voyage of the Dawn ___", answer: "Treader" },
    { clue: "The ___ Chair", answer: "Silver" },
    { clue: "The Horse and His ___", answer: "Boy" },
    { clue: "The Magician's ___", answer: "Nephew" },
    { clue: "The ___ Battle", answer: "Last" },
    { clue: "Mere ___", answer: "Christianity" },
    { clue: "The ___ Letters", answer: "Screwtape" },
    { clue: "The Problem of ___", answer: "Pain" },
    { clue: "The Great ___", answer: "Divorce" },
    { clue: "The Four ___", answer: "Loves" },
    { clue: "Surprised by ___", answer: "Joy" },
    { clue: "A Grief ___", answer: "Observed" },
    { clue: "The Abolition of ___", answer: "Man" },
    { clue: "___ We Have Faces", answer: "Till" },
    { clue: "Out of the ___ Planet", answer: "Silent" },
    { clue: "That Hideous ___", answer: "Strength" },
    { clue: "Letters to ___: Chiefly on Prayer", answer: "Malcolm" },
    { clue: "The ___ of Glory", answer: "Weight" },
    { clue: "Reflections on the ___", answer: "Psalms" },
    { clue: "The World's ___ Words", answer: "Last" },
    { clue: "God in the ___", answer: "Dock" },
    { clue: "The ___ Image", answer: "Discarded" },
    { clue: "An Experiment in ___", answer: "Criticism" },
    { clue: "Studies in ___", answer: "Words" },
    { clue: "The Pilgrim's ___", answer: "Regress" },
    { clue: "The ___ and the Glory", answer: "Joyful" },
    { clue: "Of Other ___", answer: "Worlds" },
    { clue: "Present ___", answer: "Concerns" },
  ],
};

export const CATEGORY_NAMES = Object.keys(CATEGORY_LIBRARY);
