// Pre-built category library with 15+ clues each
// Players can pick from these during setup, and host can still upload images on top

export const CATEGORY_LIBRARY = {
  "Animals": [
    { clue: "King of the jungle", answer: "Lion" },
    { clue: "Black and white bamboo eater", answer: "Panda" },
    { clue: "Tallest land animal", answer: "Giraffe" },
    { clue: "Largest ocean mammal", answer: "Blue Whale" },
    { clue: "Striped horse-like animal", answer: "Zebra" },
    { clue: "Pouch-carrying Australian hopper", answer: "Kangaroo" },
    { clue: "Eight-armed ocean creature", answer: "Octopus" },
    { clue: "Slow-moving shell carrier", answer: "Turtle" },
    { clue: "Man's best friend", answer: "Dog" },
    { clue: "Night hunter with silent wings", answer: "Owl" },
    { clue: "Trunk and big ears", answer: "Elephant" },
    { clue: "Colorful tropical talker", answer: "Parrot" },
    { clue: "Fastest land animal", answer: "Cheetah" },
    { clue: "Venomous eight-legged spinner", answer: "Spider" },
    { clue: "Hump-backed desert traveler", answer: "Camel" },
    { clue: "Pink long-legged wading bird", answer: "Flamingo" },
    { clue: "Masked nocturnal trash raider", answer: "Raccoon" },
  ],
  "Bible Characters": [
    { clue: "Built an ark for the flood", answer: "Noah" },
    { clue: "Shepherd boy who defeated a giant", answer: "David" },
    { clue: "Swallowed by a great fish", answer: "Jonah" },
    { clue: "Strongest man in the Bible", answer: "Samson" },
    { clue: "First man created by God", answer: "Adam" },
    { clue: "Led Israel out of Egypt", answer: "Moses" },
    { clue: "Sold into slavery by brothers", answer: "Joseph" },
    { clue: "Denied Jesus three times", answer: "Peter" },
    { clue: "Wise king who built the temple", answer: "Solomon" },
    { clue: "Thrown into the lions den", answer: "Daniel" },
    { clue: "Tax collector who climbed a tree", answer: "Zacchaeus" },
    { clue: "Mother of Jesus", answer: "Mary" },
    { clue: "Betrayed Jesus for 30 silver coins", answer: "Judas" },
    { clue: "First murderer in the Bible", answer: "Cain" },
    { clue: "Father of many nations", answer: "Abraham" },
    { clue: "Rebuilt the walls of Jerusalem", answer: "Nehemiah" },
  ],
  "Worship Songs": [
    { clue: "How great is our ___", answer: "God" },
    { clue: "Amazing ___ how sweet the sound", answer: "Grace" },
    { clue: "10,000 reasons to bless the ___", answer: "Lord" },
    { clue: "Way maker, miracle ___", answer: "Worker" },
    { clue: "What a beautiful ___ we carry", answer: "Name" },
    { clue: "Reckless ___", answer: "Love" },
    { clue: "Good good ___", answer: "Father" },
    { clue: "Build my life upon Your ___", answer: "Love" },
    { clue: "No longer ___ but alive in Christ", answer: "Slaves" },
    { clue: "Here I am to ___", answer: "Worship" },
    { clue: "Oceans where feet may ___", answer: "Fail" },
    { clue: "Great are You ___", answer: "Lord" },
    { clue: "In Christ ___ my hope is found", answer: "Alone" },
    { clue: "Holy ___ You are worthy", answer: "Spirit" },
    { clue: "Blessed be Your ___", answer: "Name" },
  ],
  "Movies": [
    { clue: "Boy wizard with a lightning scar", answer: "Harry Potter" },
    { clue: "Ogre who lives in a swamp", answer: "Shrek" },
    { clue: "Let it go, ice powers princess", answer: "Frozen" },
    { clue: "Toys come alive when no one looks", answer: "Toy Story" },
    { clue: "A galaxy far far away", answer: "Star Wars" },
    { clue: "Finding a lost clownfish son", answer: "Finding Nemo" },
    { clue: "Superhero team with infinity stones", answer: "Avengers" },
    { clue: "Boy raised by jungle animals", answer: "Jungle Book" },
    { clue: "Ring must be destroyed in a volcano", answer: "Lord of the Rings" },
    { clue: "Dinosaur theme park gone wrong", answer: "Jurassic Park" },
    { clue: "Lion cub becomes king of Pride Rock", answer: "Lion King" },
    { clue: "Spider-bitten teen becomes a hero", answer: "Spider-Man" },
    { clue: "Dream within a dream within a dream", answer: "Inception" },
    { clue: "Robot cleans up Earth alone", answer: "Wall-E" },
    { clue: "Genie in a lamp grants wishes", answer: "Aladdin" },
    { clue: "Italian plumber saves a princess", answer: "Mario" },
  ],
  "Countries": [
    { clue: "Land of the rising sun", answer: "Japan" },
    { clue: "Home of the Eiffel Tower", answer: "France" },
    { clue: "Great Wall is here", answer: "China" },
    { clue: "Land of kangaroos and koalas", answer: "Australia" },
    { clue: "Boot-shaped European country", answer: "Italy" },
    { clue: "Home of the Amazon rainforest", answer: "Brazil" },
    { clue: "Pyramids and the Sphinx", answer: "Egypt" },
    { clue: "Maple leaf flag country", answer: "Canada" },
    { clue: "Land of tacos and sombreros", answer: "Mexico" },
    { clue: "Taj Mahal is located here", answer: "India" },
    { clue: "Dracula's homeland in Eastern Europe", answer: "Romania" },
    { clue: "Largest country by land area", answer: "Russia" },
    { clue: "Land of Vikings and fjords", answer: "Norway" },
    { clue: "Island nation famous for sushi", answer: "Japan" },
    { clue: "Home of Big Ben and the Queen", answer: "England" },
    { clue: "Land of tulips and windmills", answer: "Netherlands" },
  ],
  "Food & Drinks": [
    { clue: "Italian pie with cheese and sauce", answer: "Pizza" },
    { clue: "Frozen treat on a cone", answer: "Ice Cream" },
    { clue: "Morning drink made from beans", answer: "Coffee" },
    { clue: "Yellow curved tropical fruit", answer: "Banana" },
    { clue: "Fizzy brown cola drink", answer: "Coca-Cola" },
    { clue: "Japanese rolled rice and fish", answer: "Sushi" },
    { clue: "Mexican wrapped tortilla meal", answer: "Burrito" },
    { clue: "Chocolate chip baked treat", answer: "Cookie" },
    { clue: "Red sauce pasta dish", answer: "Spaghetti" },
    { clue: "Grilled patty in a bun", answer: "Hamburger" },
    { clue: "Fried potato sticks", answer: "French Fries" },
    { clue: "Morning meal with syrup", answer: "Pancakes" },
    { clue: "Bubbly Italian water drink", answer: "Sparkling Water" },
    { clue: "Crunchy Mexican corn chip", answer: "Nachos" },
    { clue: "Layered Italian pasta dish", answer: "Lasagna" },
  ],
  "Sports": [
    { clue: "Dribbling and slam dunks", answer: "Basketball" },
    { clue: "Touchdown and field goals", answer: "Football" },
    { clue: "Home run and batting", answer: "Baseball" },
    { clue: "Goals, pitch, and offsides", answer: "Soccer" },
    { clue: "Love means zero in this sport", answer: "Tennis" },
    { clue: "Puck on ice with sticks", answer: "Hockey" },
    { clue: "18 holes and a tiny white ball", answer: "Golf" },
    { clue: "Pins and a heavy rolling ball", answer: "Bowling" },
    { clue: "Net, sand, and spikes", answer: "Volleyball" },
    { clue: "Gloves and a knockout punch", answer: "Boxing" },
    { clue: "Flip, vault, and balance beam", answer: "Gymnastics" },
    { clue: "Laps in a pool", answer: "Swimming" },
    { clue: "Racket and shuttlecock", answer: "Badminton" },
    { clue: "Hurdles and sprinting on a track", answer: "Track and Field" },
    { clue: "Board and waves", answer: "Surfing" },
  ],
  "Video Games": [
    { clue: "Block-building survival sandbox", answer: "Minecraft" },
    { clue: "Battle royale with building", answer: "Fortnite" },
    { clue: "Plumber rescues a princess", answer: "Super Mario" },
    { clue: "Catch them all with Pokeballs", answer: "Pokemon" },
    { clue: "Green hero saves Hyrule", answer: "Zelda" },
    { clue: "Blue hedgehog runs fast", answer: "Sonic" },
    { clue: "Soccer with rocket-powered cars", answer: "Rocket League" },
    { clue: "Block-stacking puzzle from Russia", answer: "Tetris" },
    { clue: "Five nights surviving animatronics", answer: "FNAF" },
    { clue: "Among us crewmates and imposters", answer: "Among Us" },
    { clue: "Open world horse-riding cowboys", answer: "Red Dead Redemption" },
    { clue: "Plant defenders against undead", answer: "Plants vs Zombies" },
    { clue: "Italian brothers in go-karts", answer: "Mario Kart" },
    { clue: "Blocky characters in a battle arena", answer: "Roblox" },
    { clue: "Tiny fighters on a big stage", answer: "Smash Bros" },
  ],
  "Books of the Bible": [
    { clue: "First book, creation story", answer: "Genesis" },
    { clue: "Israel leaves Egypt", answer: "Exodus" },
    { clue: "Songs and poems of praise", answer: "Psalms" },
    { clue: "Wisdom sayings of Solomon", answer: "Proverbs" },
    { clue: "Prophecy about a coming Messiah", answer: "Isaiah" },
    { clue: "Story of a faithful foreign woman", answer: "Ruth" },
    { clue: "Jesus birth and ministry, first Gospel", answer: "Matthew" },
    { clue: "Early church history and missions", answer: "Acts" },
    { clue: "Paul writes about faith and grace", answer: "Romans" },
    { clue: "Love chapter is in this letter", answer: "1 Corinthians" },
    { clue: "Apocalyptic visions and the end", answer: "Revelation" },
    { clue: "The shortest Gospel", answer: "Mark" },
    { clue: "Man tested by suffering and loss", answer: "Job" },
    { clue: "Walls rebuilt around Jerusalem", answer: "Nehemiah" },
    { clue: "Queen who saved her people", answer: "Esther" },
    { clue: "Prophet swallowed by a fish", answer: "Jonah" },
  ],
  "Flags": [
    { clue: "Red white and blue with stars and stripes", answer: "USA" },
    { clue: "Red circle on white background", answer: "Japan" },
    { clue: "Maple leaf on red and white", answer: "Canada" },
    { clue: "Green white and red vertical stripes", answer: "Italy" },
    { clue: "Blue white and red horizontal stripes", answer: "France" },
    { clue: "Union Jack cross pattern", answer: "United Kingdom" },
    { clue: "Green and gold with a diamond", answer: "Brazil" },
    { clue: "Red with five yellow stars", answer: "China" },
    { clue: "Orange white and green horizontal", answer: "India" },
    { clue: "Blue yellow and red vertical stripes", answer: "Romania" },
    { clue: "Black red and gold horizontal", answer: "Germany" },
    { clue: "Red and white with crescent moon", answer: "Turkey" },
    { clue: "Blue with yellow stars in a circle", answer: "European Union" },
    { clue: "Green with a white crescent and star", answer: "Pakistan" },
    { clue: "White cross on a red background", answer: "Switzerland" },
  ],
  "Dinosaurs": [
    { clue: "King of the dinosaurs, tiny arms", answer: "T-Rex" },
    { clue: "Three horns and a frill", answer: "Triceratops" },
    { clue: "Long neck gentle giant", answer: "Brachiosaurus" },
    { clue: "Plates along its back", answer: "Stegosaurus" },
    { clue: "Clever pack hunter with claws", answer: "Velociraptor" },
    { clue: "Flying reptile, not a dinosaur", answer: "Pterodactyl" },
    { clue: "Armored tank with a club tail", answer: "Ankylosaurus" },
    { clue: "Sail-backed meat eater", answer: "Spinosaurus" },
    { clue: "Duck-billed herbivore", answer: "Parasaurolophus" },
    { clue: "Tiny two-legged fast runner", answer: "Compsognathus" },
    { clue: "Largest land predator ever", answer: "Giganotosaurus" },
    { clue: "Dome-headed headbutter", answer: "Pachycephalosaurus" },
    { clue: "Giant ocean predator, not a dino", answer: "Mosasaurus" },
    { clue: "Feathered early bird ancestor", answer: "Archaeopteryx" },
    { clue: "Huge South American herbivore", answer: "Argentinosaurus" },
  ],
  "Candy & Snacks": [
    { clue: "Colorful button-shaped chocolates", answer: "M&Ms" },
    { clue: "Twisted salty baked dough", answer: "Pretzel" },
    { clue: "Rainbow-colored fruit chews", answer: "Skittles" },
    { clue: "Chocolate bar with caramel and nougat", answer: "Snickers" },
    { clue: "Gummy bear-shaped candies", answer: "Gummy Bears" },
    { clue: "Red and white peppermint stick", answer: "Candy Cane" },
    { clue: "Orange cheese-dusted puffs", answer: "Cheetos" },
    { clue: "Peanut butter inside chocolate cups", answer: "Reeses" },
    { clue: "Sour worm-shaped gummies", answer: "Sour Worms" },
    { clue: "Crunchy triangle-shaped corn chips", answer: "Doritos" },
    { clue: "Swirled red and white hard candy", answer: "Peppermint" },
    { clue: "Chocolate-covered wafer fingers", answer: "Kit Kat" },
    { clue: "Tiny colorful candy-coated beans", answer: "Jelly Beans" },
    { clue: "Crunchy goldfish-shaped crackers", answer: "Goldfish" },
    { clue: "Hard candy on a stick", answer: "Lollipop" },
  ],
  "Space": [
    { clue: "Closest star to Earth", answer: "Sun" },
    { clue: "Red planet, possible future home", answer: "Mars" },
    { clue: "Planet with famous rings", answer: "Saturn" },
    { clue: "Earths only natural satellite", answer: "Moon" },
    { clue: "Largest planet in our system", answer: "Jupiter" },
    { clue: "Milky spiral we live in", answer: "Milky Way" },
    { clue: "Icy space traveler with a tail", answer: "Comet" },
    { clue: "Was a planet, now a dwarf", answer: "Pluto" },
    { clue: "First man to walk on the moon", answer: "Neil Armstrong" },
    { clue: "Orbiting telescope named after a scientist", answer: "Hubble" },
    { clue: "Invisible space trap, nothing escapes", answer: "Black Hole" },
    { clue: "Explosive death of a massive star", answer: "Supernova" },
    { clue: "Space agency with the rocket logo", answer: "NASA" },
    { clue: "International home orbiting Earth", answer: "ISS" },
    { clue: "Hottest planet due to greenhouse gases", answer: "Venus" },
  ],
  "Dog Breeds": [
    { clue: "Golden friendly family dog", answer: "Golden Retriever" },
    { clue: "Spotted firehouse mascot", answer: "Dalmatian" },
    { clue: "Tiny purse-sized Mexican dog", answer: "Chihuahua" },
    { clue: "Wrinkly-faced snoring companion", answer: "Bulldog" },
    { clue: "German police and military dog", answer: "German Shepherd" },
    { clue: "Fluffy white cloud-like small dog", answer: "Pomeranian" },
    { clue: "Long body, short legs, wiener shape", answer: "Dachshund" },
    { clue: "Curly hypoallergenic smart dog", answer: "Poodle" },
    { clue: "Sled-pulling Arctic working dog", answer: "Husky" },
    { clue: "Black and tan loyal guard dog", answer: "Rottweiler" },
    { clue: "Fastest dog breed, racing hound", answer: "Greyhound" },
    { clue: "Big fluffy mountain rescue dog", answer: "Saint Bernard" },
    { clue: "Small floppy-eared royal favorite", answer: "Corgi" },
    { clue: "Chocolate or yellow lab retriever", answer: "Labrador" },
    { clue: "Wrinkly Chinese fighting dog", answer: "Shar Pei" },
  ],
  "Famous Landmarks": [
    { clue: "Iron tower in Paris", answer: "Eiffel Tower" },
    { clue: "Ancient wonder in Giza Egypt", answer: "Pyramids" },
    { clue: "Green lady in New York harbor", answer: "Statue of Liberty" },
    { clue: "Leaning building in Italy", answer: "Tower of Pisa" },
    { clue: "Great stone wall across China", answer: "Great Wall" },
    { clue: "White marble tomb in India", answer: "Taj Mahal" },
    { clue: "Ancient Roman arena for gladiators", answer: "Colosseum" },
    { clue: "Giant carved faces in South Dakota", answer: "Mount Rushmore" },
    { clue: "Christ statue overlooking Rio", answer: "Christ the Redeemer" },
    { clue: "Red rock formation in Australia", answer: "Uluru" },
    { clue: "Ancient stone circle in England", answer: "Stonehenge" },
    { clue: "Tallest building in the world, Dubai", answer: "Burj Khalifa" },
    { clue: "Golden Gate crossing in San Francisco", answer: "Golden Gate Bridge" },
    { clue: "Ancient Greek hilltop temple", answer: "Parthenon" },
    { clue: "Giant carved Buddha in Japan", answer: "Great Buddha" },
  ],
  "Instruments": [
    { clue: "Six strings and a pick", answer: "Guitar" },
    { clue: "88 black and white keys", answer: "Piano" },
    { clue: "Sticks hitting stretched skins", answer: "Drums" },
    { clue: "Brass horn with three valves", answer: "Trumpet" },
    { clue: "Bow across four strings", answer: "Violin" },
    { clue: "Wooden reed wind instrument", answer: "Clarinet" },
    { clue: "Slide in and out brass instrument", answer: "Trombone" },
    { clue: "Small four-string Hawaiian instrument", answer: "Ukulele" },
    { clue: "Handheld squeezebox with buttons", answer: "Accordion" },
    { clue: "Metal keys hit with mallets", answer: "Xylophone" },
    { clue: "Double reed orchestral woodwind", answer: "Oboe" },
    { clue: "Largest string instrument", answer: "Double Bass" },
    { clue: "Silver sideways-blown wind instrument", answer: "Flute" },
    { clue: "Scottish bag-squeezed wind instrument", answer: "Bagpipes" },
    { clue: "Plucked string triangular instrument", answer: "Harp" },
  ],
  "Holidays": [
    { clue: "December 25th gift-giving celebration", answer: "Christmas" },
    { clue: "Spooky costumes and candy night", answer: "Halloween" },
    { clue: "Egg hunt and resurrection Sunday", answer: "Easter" },
    { clue: "Turkey dinner and gratitude", answer: "Thanksgiving" },
    { clue: "Hearts, chocolates, and roses", answer: "Valentines Day" },
    { clue: "Fireworks on Americas birthday", answer: "Fourth of July" },
    { clue: "Wearing green and finding clovers", answer: "St Patricks Day" },
    { clue: "New beginning at midnight countdown", answer: "New Years" },
    { clue: "Eight nights of candles and dreidels", answer: "Hanukkah" },
    { clue: "Honoring mothers with flowers", answer: "Mothers Day" },
    { clue: "Honoring working people in September", answer: "Labor Day" },
    { clue: "Remembering fallen soldiers in May", answer: "Memorial Day" },
    { clue: "Celebrating Martin Luther King Jr", answer: "MLK Day" },
    { clue: "Groundhog predicts more winter", answer: "Groundhog Day" },
    { clue: "Pancake and costume festival before Lent", answer: "Mardi Gras" },
  ],
  "Superheroes": [
    { clue: "Web-slinging New York teenager", answer: "Spider-Man" },
    { clue: "Dark knight of Gotham City", answer: "Batman" },
    { clue: "Man of steel from Krypton", answer: "Superman" },
    { clue: "Green rage monster scientist", answer: "Hulk" },
    { clue: "Genius billionaire in iron suit", answer: "Iron Man" },
    { clue: "Norse god with a hammer", answer: "Thor" },
    { clue: "Star-spangled soldier with a shield", answer: "Captain America" },
    { clue: "Amazon warrior princess", answer: "Wonder Woman" },
    { clue: "King of Wakanda", answer: "Black Panther" },
    { clue: "Fastest man alive in red suit", answer: "The Flash" },
    { clue: "Clawed mutant with healing powers", answer: "Wolverine" },
    { clue: "Underwater king of Atlantis", answer: "Aquaman" },
    { clue: "Master of mystical arts, doctor", answer: "Doctor Strange" },
    { clue: "Shrinking hero who talks to insects", answer: "Ant-Man" },
    { clue: "Green lantern ring bearer", answer: "Green Lantern" },
  ],
  "Cartoons": [
    { clue: "Yellow family in Springfield", answer: "The Simpsons" },
    { clue: "Sponge who lives in a pineapple", answer: "SpongeBob" },
    { clue: "Boy with a magic dog named Jake", answer: "Adventure Time" },
    { clue: "Talking Great Dane solves mysteries", answer: "Scooby-Doo" },
    { clue: "Pink starfish best friend", answer: "Patrick Star" },
    { clue: "Three super-powered little girls", answer: "Powerpuff Girls" },
    { clue: "Boy genius with a big head", answer: "Jimmy Neutron" },
    { clue: "Ninja turtles who love pizza", answer: "TMNT" },
    { clue: "Cat and mouse always chasing", answer: "Tom and Jerry" },
    { clue: "Avatar who controls all elements", answer: "Avatar Aang" },
    { clue: "Pink bunny and yellow duck friends", answer: "Courage the Cowardly Dog" },
    { clue: "Gravity Falls mystery twins", answer: "Gravity Falls" },
    { clue: "Ice king chasing princesses", answer: "Adventure Time" },
    { clue: "Squirrel scientist from Texas underwater", answer: "Sandy Cheeks" },
    { clue: "Regular guys at a park", answer: "Regular Show" },
  ],
  "Science": [
    { clue: "H2O chemical formula", answer: "Water" },
    { clue: "Force that keeps us on the ground", answer: "Gravity" },
    { clue: "Closest star to Earth", answer: "Sun" },
    { clue: "Building blocks of all matter", answer: "Atoms" },
    { clue: "Gas we breathe to survive", answer: "Oxygen" },
    { clue: "Speed of this is 186,000 miles per second", answer: "Light" },
    { clue: "Double helix that carries genetic code", answer: "DNA" },
    { clue: "Table with 118 elements", answer: "Periodic Table" },
    { clue: "Process plants use to make food from sunlight", answer: "Photosynthesis" },
    { clue: "Theory of evolution scientist", answer: "Darwin" },
    { clue: "E equals mc squared genius", answer: "Einstein" },
    { clue: "Layer protecting Earth from UV rays", answer: "Ozone" },
    { clue: "Molten rock erupting from Earth", answer: "Lava" },
    { clue: "Brain chemical that makes you happy", answer: "Dopamine" },
    { clue: "Smallest unit of life", answer: "Cell" },
  ],
  "C.S. Lewis Books": [
    { clue: "The ___, the Witch and the Wardrobe", answer: "Lion" },
    { clue: "Prince ___", answer: "Caspian" },
    { clue: "The Voyage of the Dawn ___", answer: "Treader" },
    { clue: "The ___ Chair", answer: "Silver" },
    { clue: "The Horse and His ___", answer: "Boy" },
    { clue: "The Magician's ___", answer: "Nephew" },
    { clue: "The ___ Battle", answer: "Last" },
    { clue: "Mere ___", answer: "Christianity" },
    { clue: "The ___ Letters", answer: "Screwtape" },
    { clue: "The Problem of ___", answer: "Pain" },
    { clue: "The Great ___", answer: "Divorce" },
    { clue: "The Four ___", answer: "Loves" },
    { clue: "Surprised by ___", answer: "Joy" },
    { clue: "A Grief ___", answer: "Observed" },
    { clue: "The Abolition of ___", answer: "Man" },
    { clue: "___ We Have Faces", answer: "Till" },
    { clue: "Out of the ___ Planet", answer: "Silent" },
    { clue: "That Hideous ___", answer: "Strength" },
    { clue: "Letters to ___: Chiefly on Prayer", answer: "Malcolm" },
    { clue: "The ___ of Glory", answer: "Weight" },
    { clue: "Reflections on the ___", answer: "Psalms" },
    { clue: "The World's ___ Words", answer: "Last" },
    { clue: "God in the ___", answer: "Dock" },
    { clue: "The ___ Image", answer: "Discarded" },
    { clue: "An Experiment in ___", answer: "Criticism" },
    { clue: "Studies in ___", answer: "Words" },
    { clue: "The Pilgrim's ___", answer: "Regress" },
    { clue: "The ___ and the Glory", answer: "Joyful" },
    { clue: "Of Other ___", answer: "Worlds" },
    { clue: "Present ___", answer: "Concerns" },
  ],
  "Computers": [
    { type: "image", src: "/images/computers/blue tooth.png", answer: "blue tooth" },
    { type: "image", src: "/images/computers/cooling fan.jpeg", answer: "cooling fan" },
    { type: "image", src: "/images/computers/cpu.jpeg", answer: "cpu" },
    { type: "image", src: "/images/computers/game controller.jpeg", answer: "game controller" },
    { type: "image", src: "/images/computers/gpu.jpeg", answer: "gpu" },
    { type: "image", src: "/images/computers/hdd.jpeg", answer: "hdd" },
    { type: "image", src: "/images/computers/hdmi.jpeg", answer: "hdmi" },
    { type: "image", src: "/images/computers/heat sink.webp", answer: "heat sink" },
    { type: "image", src: "/images/computers/joystick.webp", answer: "joystick" },
    { type: "image", src: "/images/computers/laptop.jpeg", answer: "laptop" },
    { type: "image", src: "/images/computers/liquid cooling system.jpeg", answer: "liquid cooling system" },
    { type: "image", src: "/images/computers/monitor.jpeg", answer: "monitor" },
    { type: "image", src: "/images/computers/motherbaord.jpeg", answer: "motherbaord" },
    { type: "image", src: "/images/computers/mouse.jpeg", answer: "mouse" },
    { type: "image", src: "/images/computers/mousepad.jpeg", answer: "mousepad" },
    { type: "image", src: "/images/computers/optical drive.jpeg", answer: "optical drive" },
    { type: "image", src: "/images/computers/printer.jpeg", answer: "printer" },
    { type: "image", src: "/images/computers/psu.jpeg", answer: "psu" },
    { type: "image", src: "/images/computers/RAM.jpeg", answer: "RAM" },
    { type: "image", src: "/images/computers/router.jpeg", answer: "router" },
    { type: "image", src: "/images/computers/scanner.jpeg", answer: "scanner" },
    { type: "image", src: "/images/computers/sd reader.jpeg", answer: "sd reader" },
    { type: "image", src: "/images/computers/speakers.jpeg", answer: "speakers" },
    { type: "image", src: "/images/computers/ssd.jpeg", answer: "ssd" },
    { type: "image", src: "/images/computers/sureg protector.jpeg", answer: "sureg protector" },
    { type: "image", src: "/images/computers/tower.jpeg", answer: "tower" },
    { type: "image", src: "/images/computers/trackpad.jpeg", answer: "trackpad" },
    { type: "image", src: "/images/computers/trackpad.webp", answer: "trackpad" },
    { type: "image", src: "/images/computers/usb hub.jpeg", answer: "usb hub" },
    { type: "image", src: "/images/computers/webcam.jpeg", answer: "webcam" },
  ],
  "Hunger Game Characters": [
    { type: "image", src: "/images/Hunger Game Characters/almacoin.jpeg", answer: "almacoin" },
    { type: "image", src: "/images/Hunger Game Characters/ASterid Everdeen.jpeg", answer: "ASterid Everdeen" },
    { type: "image", src: "/images/Hunger Game Characters/Atala.jpeg", answer: "Atala" },
    { type: "image", src: "/images/Hunger Game Characters/Avox Girl.jpeg", answer: "Avox Girl" },
    { type: "image", src: "/images/Hunger Game Characters/Beetee.jpeg", answer: "Beetee" },
    { type: "image", src: "/images/Hunger Game Characters/boggs.webp", answer: "boggs" },
    { type: "image", src: "/images/Hunger Game Characters/butter cup.jpeg", answer: "butter cup" },
    { type: "image", src: "/images/Hunger Game Characters/Caesar Flickerman.jpeg", answer: "Caesar Flickerman" },
    { type: "image", src: "/images/Hunger Game Characters/Cashmere.jpeg", answer: "Cashmere" },
    { type: "image", src: "/images/Hunger Game Characters/castor.jpeg", answer: "castor" },
    { type: "image", src: "/images/Hunger Game Characters/Cato.jpeg", answer: "Cato" },
    { type: "image", src: "/images/Hunger Game Characters/Cinna.jpeg", answer: "Cinna" },
    { type: "image", src: "/images/Hunger Game Characters/Claudius Templesmith.jpeg", answer: "Claudius Templesmith" },
    { type: "image", src: "/images/Hunger Game Characters/Clove.jpeg", answer: "Clove" },
    { type: "image", src: "/images/Hunger Game Characters/commander paylor.jpeg", answer: "commander paylor" },
    { type: "image", src: "/images/Hunger Game Characters/dk.jpeg", answer: "dk" },
    { type: "image", src: "/images/Hunger Game Characters/effie.jpeg", answer: "effie" },
    { type: "image", src: "/images/Hunger Game Characters/Enobaria.jpeg", answer: "Enobaria" },
    { type: "image", src: "/images/Hunger Game Characters/Flavius.jpeg", answer: "Flavius" },
    { type: "image", src: "/images/Hunger Game Characters/Foxface.jpeg", answer: "Foxface" },
    { type: "image", src: "/images/Hunger Game Characters/Gale.jpeg", answer: "Gale" },
    { type: "image", src: "/images/Hunger Game Characters/Glimmer.jpeg", answer: "Glimmer" },
    { type: "image", src: "/images/Hunger Game Characters/Gloss.jpeg", answer: "Gloss" },
    { type: "image", src: "/images/Hunger Game Characters/haymitch.jpeg", answer: "haymitch" },
    { type: "image", src: "/images/Hunger Game Characters/Johanna.jpeg", answer: "Johanna" },
    { type: "image", src: "/images/Hunger Game Characters/joshua hong.jpeg", answer: "joshua hong" },
    { type: "image", src: "/images/Hunger Game Characters/Katniss.jpeg", answer: "Katniss" },
    { type: "image", src: "/images/Hunger Game Characters/Mags.jpeg", answer: "Mags" },
    { type: "image", src: "/images/Hunger Game Characters/Marvel.jpeg", answer: "Marvel" },
    { type: "image", src: "/images/Hunger Game Characters/Octavia.jpeg", answer: "Octavia" },
    { type: "image", src: "/images/Hunger Game Characters/peeta.jpeg", answer: "peeta" },
    { type: "image", src: "/images/Hunger Game Characters/Plutarch.jpeg", answer: "Plutarch" },
    { type: "image", src: "/images/Hunger Game Characters/pollux.jpeg", answer: "pollux" },
    { type: "image", src: "/images/Hunger Game Characters/Portia.jpeg", answer: "Portia" },
    { type: "image", src: "/images/Hunger Game Characters/president snow.jpeg", answer: "president snow" },
    { type: "image", src: "/images/Hunger Game Characters/primrose.jpeg", answer: "primrose" },
    { type: "image", src: "/images/Hunger Game Characters/Rue.jpeg", answer: "Rue" },
    { type: "image", src: "/images/Hunger Game Characters/Seneca Crane.jpeg", answer: "Seneca Crane" },
    { type: "image", src: "/images/Hunger Game Characters/Thresh.jpeg", answer: "Thresh" },
    { type: "image", src: "/images/Hunger Game Characters/tigris.jpeg", answer: "tigris" },
    { type: "image", src: "/images/Hunger Game Characters/Wiress.jpeg", answer: "Wiress" },
  ],
  "Instruments (Images)": [
    { type: "image", src: "/images/instruments/bagpipe.jpeg", answer: "bagpipe" },
    { type: "image", src: "/images/instruments/banjo.jpeg", answer: "banjo" },
    { type: "image", src: "/images/instruments/digeridoo.jpeg", answer: "digeridoo" },
    { type: "image", src: "/images/instruments/djembe.jpeg", answer: "djembe" },
    { type: "image", src: "/images/instruments/erhu.jpeg", answer: "erhu" },
    { type: "image", src: "/images/instruments/fluggelhorn.jpeg", answer: "fluggelhorn" },
    { type: "image", src: "/images/instruments/guitar.jpeg", answer: "guitar" },
    { type: "image", src: "/images/instruments/harmonica.jpeg", answer: "harmonica" },
    { type: "image", src: "/images/instruments/kalimba.jpeg", answer: "kalimba" },
    { type: "image", src: "/images/instruments/mandolin.jpeg", answer: "mandolin" },
    { type: "image", src: "/images/instruments/oboe.jpeg", answer: "oboe" },
    { type: "image", src: "/images/instruments/piano.jpeg", answer: "piano" },
    { type: "image", src: "/images/instruments/piccolo.jpeg", answer: "piccolo" },
    { type: "image", src: "/images/instruments/saxophone.jpeg", answer: "saxophone" },
    { type: "image", src: "/images/instruments/sitar.jpeg", answer: "sitar" },
    { type: "image", src: "/images/instruments/snare drum.jpeg", answer: "snare drum" },
    { type: "image", src: "/images/instruments/synthesizer.jpeg", answer: "synthesizer" },
    { type: "image", src: "/images/instruments/trumpet.jpeg", answer: "trumpet" },
    { type: "image", src: "/images/instruments/ukelele.jpeg", answer: "ukelele" },
    { type: "image", src: "/images/instruments/vibraphone.jpeg", answer: "vibraphone" },
    { type: "image", src: "/images/instruments/violin.jpeg", answer: "violin" },
  ],
  "Kpop": [
    { type: "image", src: "/images/Kpop/bang chan.jpeg", answer: "bang chan" },
    { type: "image", src: "/images/Kpop/changbin.jpeg", answer: "changbin" },
    { type: "image", src: "/images/Kpop/chenle.jpeg", answer: "chenle" },
    { type: "image", src: "/images/Kpop/choi john-go.jpeg", answer: "choi john go" },
    { type: "image", src: "/images/Kpop/dowoon.jpeg", answer: "dowoon" },
    { type: "image", src: "/images/Kpop/felix.jpeg", answer: "felix" },
    { type: "image", src: "/images/Kpop/haechan.jpeg", answer: "haechan" },
    { type: "image", src: "/images/Kpop/han.jpeg", answer: "han" },
    { type: "image", src: "/images/Kpop/hoshi.jpeg", answer: "hoshi" },
    { type: "image", src: "/images/Kpop/hwang yi li.jpeg", answer: "hwang yi li" },
    { type: "image", src: "/images/Kpop/hyujin.jpeg", answer: "hyujin" },
    { type: "image", src: "/images/Kpop/I.N", answer: "I.N" },
    { type: "image", src: "/images/Kpop/j-hope.jpeg", answer: "j hope" },
    { type: "image", src: "/images/Kpop/jaemin.jpeg", answer: "jaemin" },
    { type: "image", src: "/images/Kpop/jennie.jpeg", answer: "jennie" },
    { type: "image", src: "/images/Kpop/jeno.jpeg", answer: "jeno" },
    { type: "image", src: "/images/Kpop/jimin.jpeg", answer: "jimin" },
    { type: "image", src: "/images/Kpop/jin.jpeg", answer: "jin" },
    { type: "image", src: "/images/Kpop/jisoo.jpeg", answer: "jisoo" },
    { type: "image", src: "/images/Kpop/jisung.jpeg", answer: "jisung" },
    { type: "image", src: "/images/Kpop/jung kook.jpeg", answer: "jung kook" },
    { type: "image", src: "/images/Kpop/kim woojin.jpeg", answer: "kim woojin" },
    { type: "image", src: "/images/Kpop/lee know.jpeg", answer: "lee know" },
    { type: "image", src: "/images/Kpop/lia.jpeg", answer: "lia" },
    { type: "image", src: "/images/Kpop/lisa.jpeg", answer: "lisa" },
    { type: "image", src: "/images/Kpop/mark lee.jpeg", answer: "mark lee" },
    { type: "image", src: "/images/Kpop/mingyu.jpeg", answer: "mingyu" },
    { type: "image", src: "/images/Kpop/renjun.jpeg", answer: "renjun" },
    { type: "image", src: "/images/Kpop/rm.jpeg", answer: "rm" },
    { type: "image", src: "/images/Kpop/rose.jpeg", answer: "rose" },
    { type: "image", src: "/images/Kpop/ryujin.jpeg", answer: "ryujin" },
    { type: "image", src: "/images/Kpop/san.jpeg", answer: "san" },
    { type: "image", src: "/images/Kpop/seong wha.jpeg", answer: "seong wha" },
    { type: "image", src: "/images/Kpop/seungmin.jpeg", answer: "seungmin" },
    { type: "image", src: "/images/Kpop/seungwhon.jpeg", answer: "seungwhon" },
    { type: "image", src: "/images/Kpop/song min-gi.jpeg", answer: "song min gi" },
    { type: "image", src: "/images/Kpop/suga.jpeg", answer: "suga" },
    { type: "image", src: "/images/Kpop/the8.jpeg", answer: "the8" },
    { type: "image", src: "/images/Kpop/v.jpeg", answer: "v" },
    { type: "image", src: "/images/Kpop/vernon.jpeg", answer: "vernon" },
    { type: "image", src: "/images/Kpop/wen junhui.jpeg", answer: "wen junhui" },
    { type: "image", src: "/images/Kpop/wonmoo.jpeg", answer: "wonmoo" },
    { type: "image", src: "/images/Kpop/woozi.jpeg", answer: "woozi" },
    { type: "image", src: "/images/Kpop/yoon jeonghon.jpeg", answer: "yoon jeonghon" },
    { type: "image", src: "/images/Kpop/yuna.jpeg", answer: "yuna" },
  ],
  "Pokemon": [
    { type: "image", src: "/images/Pokemon/arbok.png", answer: "arbok" },
    { type: "image", src: "/images/Pokemon/beedrill.png", answer: "beedrill" },
    { type: "image", src: "/images/Pokemon/bell sprout.png", answer: "bell sprout" },
    { type: "image", src: "/images/Pokemon/blastoise.png", answer: "blastoise" },
    { type: "image", src: "/images/Pokemon/bulbasaur.png", answer: "bulbasaur" },
    { type: "image", src: "/images/Pokemon/butter free.png", answer: "butter free" },
    { type: "image", src: "/images/Pokemon/caterpie.png", answer: "caterpie" },
    { type: "image", src: "/images/Pokemon/chansey.png", answer: "chansey" },
    { type: "image", src: "/images/Pokemon/charizard.png", answer: "charizard" },
    { type: "image", src: "/images/Pokemon/charmander.png", answer: "charmander" },
    { type: "image", src: "/images/Pokemon/charmeleon.png", answer: "charmeleon" },
    { type: "image", src: "/images/Pokemon/clefair.png", answer: "clefair" },
    { type: "image", src: "/images/Pokemon/cubone.png", answer: "cubone" },
    { type: "image", src: "/images/Pokemon/diglett.png", answer: "diglett" },
    { type: "image", src: "/images/Pokemon/eevee.png", answer: "eevee" },
    { type: "image", src: "/images/Pokemon/farfetchd.png", answer: "farfetchd" },
    { type: "image", src: "/images/Pokemon/gastly.png", answer: "gastly" },
    { type: "image", src: "/images/Pokemon/gengar.png", answer: "gengar" },
    { type: "image", src: "/images/Pokemon/geodude.png", answer: "geodude" },
    { type: "image", src: "/images/Pokemon/golem.png", answer: "golem" },
    { type: "image", src: "/images/Pokemon/gyarados.png", answer: "gyarados" },
    { type: "image", src: "/images/Pokemon/ivy saur.png", answer: "ivy saur" },
    { type: "image", src: "/images/Pokemon/jigglypuff.png", answer: "jigglypuff" },
    { type: "image", src: "/images/Pokemon/jolteon.png", answer: "jolteon" },
    { type: "image", src: "/images/Pokemon/kadaabra.png", answer: "kadaabra" },
    { type: "image", src: "/images/Pokemon/kakuna.png", answer: "kakuna" },
    { type: "image", src: "/images/Pokemon/kangashkan.png", answer: "kangashkan" },
    { type: "image", src: "/images/Pokemon/magkarp.png", answer: "magkarp" },
    { type: "image", src: "/images/Pokemon/magmar.png", answer: "magmar" },
    { type: "image", src: "/images/Pokemon/meowth.png", answer: "meowth" },
    { type: "image", src: "/images/Pokemon/metapod.png", answer: "metapod" },
    { type: "image", src: "/images/Pokemon/mew.png", answer: "mew" },
    { type: "image", src: "/images/Pokemon/mewtwo.png", answer: "mewtwo" },
    { type: "image", src: "/images/Pokemon/mr mime.png", answer: "mr mime" },
    { type: "image", src: "/images/Pokemon/onix.png", answer: "onix" },
    { type: "image", src: "/images/Pokemon/pearow.png", answer: "pearow" },
    { type: "image", src: "/images/Pokemon/pidgey.png", answer: "pidgey" },
    { type: "image", src: "/images/Pokemon/pikachu.png", answer: "pikachu" },
    { type: "image", src: "/images/Pokemon/poliwag.png", answer: "poliwag" },
    { type: "image", src: "/images/Pokemon/psyduck.png", answer: "psyduck" },
    { type: "image", src: "/images/Pokemon/raichu.png", answer: "raichu" },
    { type: "image", src: "/images/Pokemon/raticate.png", answer: "raticate" },
    { type: "image", src: "/images/Pokemon/rattata.png", answer: "rattata" },
    { type: "image", src: "/images/Pokemon/sandshrew.png", answer: "sandshrew" },
    { type: "image", src: "/images/Pokemon/sandslash.png", answer: "sandslash" },
    { type: "image", src: "/images/Pokemon/slowpoke.png", answer: "slowpoke" },
    { type: "image", src: "/images/Pokemon/snorlax.png", answer: "snorlax" },
    { type: "image", src: "/images/Pokemon/squirtle.png", answer: "squirtle" },
    { type: "image", src: "/images/Pokemon/staryu.png", answer: "staryu" },
    { type: "image", src: "/images/Pokemon/tentacool.png", answer: "tentacool" },
    { type: "image", src: "/images/Pokemon/venusaur.png", answer: "venusaur" },
    { type: "image", src: "/images/Pokemon/vulpix.png", answer: "vulpix" },
    { type: "image", src: "/images/Pokemon/wartortle.png", answer: "wartortle" },
    { type: "image", src: "/images/Pokemon/weed;e.png", answer: "weed;e" },
    { type: "image", src: "/images/Pokemon/zubat.png", answer: "zubat" },
  ],
  "Video Game Characters": [
    { type: "image", src: "/images/Video game characters/agent 47.jpeg", answer: "agent 47" },
    { type: "image", src: "/images/Video game characters/alex.jpeg", answer: "alex" },
    { type: "image", src: "/images/Video game characters/amy.jpeg", answer: "amy" },
    { type: "image", src: "/images/Video game characters/arthur morgna.jpeg", answer: "arthur morgna" },
    { type: "image", src: "/images/Video game characters/bowser.jpeg", answer: "bowser" },
    { type: "image", src: "/images/Video game characters/bratos.jpeg", answer: "bratos" },
    { type: "image", src: "/images/Video game characters/captain price.jpeg", answer: "captain price" },
    { type: "image", src: "/images/Video game characters/chun li.jpeg", answer: "chun li" },
    { type: "image", src: "/images/Video game characters/cloud strife.jpeg", answer: "cloud strife" },
    { type: "image", src: "/images/Video game characters/crash bandicoot.jpeg", answer: "crash bandicoot" },
    { type: "image", src: "/images/Video game characters/doomguy.jpeg", answer: "doomguy" },
    { type: "image", src: "/images/Video game characters/Ezio.jpeg", answer: "Ezio" },
    { type: "image", src: "/images/Video game characters/goro.jpeg", answer: "goro" },
    { type: "image", src: "/images/Video game characters/johnny cage.webp", answer: "johnny cage" },
    { type: "image", src: "/images/Video game characters/kassandra.jpeg", answer: "kassandra" },
    { type: "image", src: "/images/Video game characters/kazuma kiryu.jpeg", answer: "kazuma kiryu" },
    { type: "image", src: "/images/Video game characters/ken.jpeg", answer: "ken" },
    { type: "image", src: "/images/Video game characters/kirby.jpeg", answer: "kirby" },
    { type: "image", src: "/images/Video game characters/lara croft.jpeg", answer: "lara croft" },
    { type: "image", src: "/images/Video game characters/link.jpeg", answer: "link" },
    { type: "image", src: "/images/Video game characters/m. bison.jpeg", answer: "m. bison" },
    { type: "image", src: "/images/Video game characters/mario.jpeg", answer: "mario" },
    { type: "image", src: "/images/Video game characters/master chief.jpeg", answer: "master chief" },
    { type: "image", src: "/images/Video game characters/nash.jpeg", answer: "nash" },
    { type: "image", src: "/images/Video game characters/nathan drake .jpeg", answer: "nathan drake" },
    { type: "image", src: "/images/Video game characters/niko bellic.jpeg", answer: "niko bellic" },
    { type: "image", src: "/images/Video game characters/pacman.jpeg", answer: "pacman" },
    { type: "image", src: "/images/Video game characters/pikachu.jpeg", answer: "pikachu" },
    { type: "image", src: "/images/Video game characters/red toad.jpeg", answer: "red toad" },
    { type: "image", src: "/images/Video game characters/ryu.jpeg", answer: "ryu" },
    { type: "image", src: "/images/Video game characters/sackboy.jpeg", answer: "sackboy" },
    { type: "image", src: "/images/Video game characters/scorpion.jpeg", answer: "scorpion" },
    { type: "image", src: "/images/Video game characters/solid snake.jpeg", answer: "solid snake" },
    { type: "image", src: "/images/Video game characters/sonic.jpeg", answer: "sonic" },
    { type: "image", src: "/images/Video game characters/steve.jpeg", answer: "steve" },
    { type: "image", src: "/images/Video game characters/tom nook.jpeg", answer: "tom nook" },
    { type: "image", src: "/images/Video game characters/yoshi.jpeg", answer: "yoshi" },
    { type: "image", src: "/images/Video game characters/zuri.jpeg", answer: "zuri" },
  ],
};

export const CATEGORY_NAMES = Object.keys(CATEGORY_LIBRARY);
